<?php
include_once __DIR__ . '/layouts/head.phtml';
include_once __DIR__ . '/layouts/navbar.phtml';
include_once __DIR__ . '/layouts/sidebar.phtml';

?>
<!-- .app-main -->
<main class="app-main">
    <!-- .wrapper -->
    <div class="wrapper">
        <!-- .page -->
        <div class="page">
            <!-- .page-inner -->
            <div class="page-inner">
                <div class="page-section">

                </div>

            </div><!-- /.page-inner -->
        </div><!-- /.page -->
    </div><!-- .app-footer -->

    <!-- /.wrapper -->
</main><!-- /.app-main -->

<?php
include_once __DIR__ . '/layouts/footer.phtml';
include_once __DIR__ . '/layouts/script.phtml';
include_once __DIR__ . '/layouts/end.phtml';
?>