<?php
include_once __DIR__ . '/layouts/head.phtml';
include_once __DIR__ . '/layouts/navbar.phtml';
include_once __DIR__ . '/layouts/sidebar.phtml';

?>
<!-- .app-main -->
<main class="app-main">
    <!-- .wrapper -->
    <div class="wrapper">
        <!-- .page -->
        <div class="page">
            <!-- .page-inner -->
            <div class="page-inner">
            <div class="page-section">
            <div class="card card-fluid">
              <h6 class="card-header">Cài đặt chung</h6>
              <!-- .card-body -->
              <div class="card-body">
                <form method="post" action="/api/admin/setting/update" data-ajax>
                  <div class="form-group mb-4">
                    <div class="form-label-group">
                      <input type="text" id="title" name="title" class="form-control" value="<?=Site::get("title");?>" autocomplete="off" data-parsley-group="fieldset01" required="">
                      <label for="title">Tiêu đề</label>
                    </div>
                    <small class="form-text text-muted">
                      <strong>Khuyến cáo:</strong>
                      Để tên thương hiệu giúp bạn tăng lượt tìm kiếm
                    </small>
                  </div>

                  <!-- .form-group -->
                  <div class="form-group mb-4">
                    <div class="form-label-group">
                      <input type="text" id="keywords" name="keywords" class="form-control" value="<?=Site::get("keywords");?>" autocomplete="off" required="">
                      <label for="keywords">Từ khóa</label>
                    </div>
                    <small class="form-text text-muted">
                      <strong>Khuyến cáo:</strong>
                      Các từ khóa dài thường có ít cạnh tranh hơn.
                    </small>
                  </div>

                  <div class="form-group mb-4">
                    <div class="form-label-group">
                      <textarea type="text" id="description" name="description" class="form-control" rows="5" required=""><?=Site::get("description");?></textarea>
                      <label for="description">Mô tả</label>
                    </div>
                    <small class="form-text text-muted">
                      Các Mô tả dài thường có ít cạnh tranh hơn.
                    </small>
                  </div>

                  <div class="form-group mb-4">
                    <div class="form-label-group">
                      <input type="text" id="partner_id" name="partner_id" class="form-control" value="<?=Site::get("partner_id");?>" autocomplete="off" >
                      <label for="partner_id">Partner ID ( Thesieure.com )</label>
                    </div>
                  </div>

                  <div class="form-group mb-4">
                    <div class="form-label-group">
                      <input type="text" id="partner_key" name="partner_key" class="form-control" value="<?=Site::get("partner_key");?>" autocomplete="off" >
                      <label for="partner_key">Partner Key ( Thesieure.com )</label>
                    </div>
                  </div>

                  <div class="form-group mb-4">
                    <div class="form-label-group">
                      <input type="text" id="signature" name="signature" class="form-control" value="<?=Site::get("signature");?>" autocomplete="off" >
                      <label for="signature">Signature ( api.sieuthicode.net )</label>
                    </div>
                  </div>
                  <hr>
                  <!-- .form-actions -->
                  <div class="form-actions">
                    <button type="submit" class="btn btn-primary ml-auto">
                      Cập nhập
                    </button>
                  </div>
                  <!-- /.form-actions -->
                </form>
                <!-- /form -->
              </div>
              <!-- /.card-body -->
            </div>
          </div>

            </div><!-- /.page-inner -->
        </div><!-- /.page -->
    </div><!-- .app-footer -->

    <!-- /.wrapper -->
</main><!-- /.app-main -->

<?php
include_once __DIR__ . '/layouts/footer.phtml';
include_once __DIR__ . '/layouts/script.phtml';
include_once __DIR__ . '/layouts/end.phtml';
?>