<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- End Required meta tags -->
    <!-- Begin SEO tag -->
    <title>Quản trị sàn thương mại điện tử</title>
    <meta property="og:title" content="Quản trị sàn thương mại điện tử" />
    <meta name="author" content="TUNGMMO" />
    <meta property="og:locale" content="vi_VN" />
    <meta name="description" content="Quản trị sàn thương mại điện tử" />
    <meta property="og:description" content="Quản trị sàn thương mại điện tử" />
    <link rel="canonical" href="/admin/" />
    <meta property="og:url" content="/admin/" />
    <meta property="og:site_name" content="Quản trị sàn thương mại điện tử" />
    <script type="application/ld+json">
        {
            "name": "Quản trị sàn thương mại điện tử",
            "description": "Quản trị sàn thương mại điện tử",
            "author": {
                "@type": "Person",
                "name": "TUNGMMO"
            },
            "@type": "WebSite",
            "url": "",
            "headline": "Sign In",
            "@context": "http://schema.org"
        }
    </script>
    <!-- End SEO tag -->
    <meta name="referrer" content="no-referrer" />

    <link
        rel="apple-touch-icon"
        sizes="144x144"
        href="/static/apple-touch-icon.png" />
    <link rel="shortcut icon" href="/static/favicon.ico" />
    <meta name="theme-color" content="#3063A0" />
    <!-- Google font -->
    <link
        href="https://fonts.googleapis.com/css?family=Fira+Sans:400,500,600"
        rel="stylesheet" />
    <!-- End Google font -->
    <!-- BEGIN PLUGINS STYLES -->
    <!-- BEGIN PLUGINS STYLES -->
    <link
        rel="stylesheet"
        href="/static/vendor/open-iconic/font/css/open-iconic-bootstrap.min.css" />
    <link
        rel="stylesheet"
        href="/static/vendor/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css" />
    <!-- END PLUGINS STYLES -->
    <link
        rel="stylesheet"
        href="//cdn.datatables.net/2.1.5/css/dataTables.dataTables.min.css" />
    <link
        rel="stylesheet"
        href="/static/vendor/@fortawesome/fontawesome-free/css/all.min.css" />
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <link
      rel="stylesheet"
      href="//cdn.datatables.net/2.1.5/css/dataTables.dataTables.min.css"
    />
    <link
      rel="stylesheet"
      href="/assets/vendor/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css"
    />
    <link
        rel="stylesheet"
        href="/static/stylesheets/theme.min.css?v"
        data-skin="default" />
    <link
        rel="stylesheet"
        href="/static/stylesheets/theme-dark.min.css?v"
        data-skin="dark" />
    <link rel="stylesheet" href="/static/stylesheets/custom.css" />
    <script>
        var skin = localStorage.getItem("skin") || "default";
        var disabledSkinStylesheet = document.querySelector(
            'link[data-skin]:not([data-skin="' + skin + '"])',
        );
        // Disable unused skin immediately
        disabledSkinStylesheet.setAttribute("rel", "");
        disabledSkinStylesheet.setAttribute("disabled", true);
        // add loading class to html immediately
        document.querySelector("html").classList.add("loading");
    </script>
    <!-- END THEME STYLES -->
    <style>
        div.dt-container .dt-paging .dt-paging-button.disabled,
        div.dt-container .dt-paging .dt-paging-button.disabled:hover,
        div.dt-container .dt-paging .dt-paging-button.disabled:active {
            color: var(--blue) !important;
        }

        div.dt-container .dt-paging .dt-paging-button.current,
        div.dt-container .dt-paging .dt-paging-button.current:hover {
            border-radius: 3px;
            border: none;
            background: var(--blue) !important;
            color: white !important;
            outline: 0;
        }

        .form-control.placeholder-shown[type="datetime-local"],
        .form-control.placeholder-shown[type="date"] {
            color: transparent;
        }

        .form-label-group textarea {
            padding-top: 1.25rem;
            padding-bottom: 0.25rem;
            height: auto;
        }

        table {
            white-space: nowrap;
        }
    </style>
</head>

<body>