    <div class="bg-white rounded-lg mt-5">
        <div class="flex items-center px-3 py-2 justify-between">
            <div class="text-base font-semibold">Cài đặt tài khoản</div>
        </div>
        <div class="border-t border-gray-300">
            <div class="px-3 py-2" id="menu-info">
                <ul class="list-none">
                    <li class="px-3 mt-1 py-2 cursor-pointer rounded-md font-semibold text-base flex items-center hover:bg-gray-200 hover:text-gray-700 text-gray-500">
                        <a class="flex items-center w-full h-full" href="/info/profile">
                            <i class="fa-solid fa-user"></i>
                            <span class="ml-2">Hồ sơ</span>
                        </a>
                    </li>
                    <li class="px-3 mt-1 py-2 cursor-pointer rounded-md font-semibold text-base flex items-center hover:bg-gray-200 hover:text-gray-700 text-gray-500">
                        <a class="flex items-center w-full h-full" href="/info/security">
                            <i class="fa-solid fa-lock"></i>
                            <span class="ml-2">Đổi mật khẩu</span>
                        </a>
                    </li>
                    <li class="px-3 mt-1 py-2 cursor-pointer rounded-md font-semibold text-base flex items-center hover:bg-gray-200 hover:text-gray-700 text-gray-500">
                        <a class="flex items-center w-full h-full" href="/info/history">
                            <i class="fa-regular fa-clock-rotate-left"></i>
                            <span class="ml-2">Lịch sử mua</span>
                        </a>
                    </li>

                    <li class="px-3 mt-1 py-2 cursor-pointer rounded-md font-semibold text-base flex items-center hover:bg-gray-200 hover:text-gray-700 text-gray-500">
                        <a class="flex items-center w-full h-full" href="/logout">
                        <i class="fa-duotone fa-regular fa-left-from-bracket"></i>
                            <span class="ml-2">Đăng xuất</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>