<?php
include_once __DIR__ . '/../layouts/head.phtml';
include_once __DIR__ . '/../layouts/navbar.phtml';
include_once __DIR__ . '/../layouts/sidebar.phtml';

?>
<div class="pt-[4rem] pb-[5rem] px-3 lg:px-[5rem]">
    <div class="lg:grid grid-cols-12 gap-5">
        <div class="col-span-12 xl:col-span-3">
            <?php include_once __DIR__ . '/menu.phtml'; ?>

        </div>
        <div class="col-span-12 xl:col-span-7">
            <div class="bg-white rounded-lg mt-5">
                <div class="flex items-center play-regular px-8 py-4 justify-between">
                    <div class="text-lg text-gray-500 font-semibold">Hồ sơ cá nhân</div>
                </div>
                <div class="border-t border-gray-300">
                    <div class="px-3 py-2">
                        <form class="space-y-4 px-5" method="POST" action="/api/info/change-profile" data-ajax>
                            <div>
                                <label class="block text-sm font-semibold">Tài khoản:
                                    <input  class="mt-1 w-full py-3 border border-gray-300 rounded-md px-3 text-sm focus:outline-none" 
                                    value="<?=Auth::user()->username?>" name="username" type="text" readonly disabled>
                                </label>
                            </div>
                            <div>
                                <label class="block text-sm font-semibold">Họ và tên:
                                    <input placeholder="Nhập họ của bạn" class="mt-1 w-full py-3 border border-gray-300 rounded-md px-3 text-sm focus:outline-none"
                                    value="<?=Auth::user()->fullname?>"
                                        name="fullname" type="text">
                                </label>
                            </div>
                            <div>
                                <label class="block text-sm font-semibold">Email:
                                    <input readonly="" 
                                    placeholder="Nhập địa chỉ email của bạn" class="mt-1 w-full py-3 border border-gray-300 rounded-md px-3 text-sm focus:outline-none" name="email" type="email" value="<?=Auth::user()->email?>">
                                </label>
                            </div>

                            <div class="pb-4">
                                <button type="submit" class="bg-blue-500 text-white px-4 w-full font-semibold rounded-md text-sm h-[3rem] play-regular ">
                                    Cập nhập
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
include_once __DIR__ . '/../layouts/footer.phtml';
include_once __DIR__ . '/../layouts/script.phtml';
include_once __DIR__ . '/../layouts/end.phtml';
?>