<footer class="bg-white">
  <div class="container px-4 lg:mx-auto py-12">
    <div class="grid grid-cols-2 md:grid-cols-6 gap-16">
      <!-- Description Section -->
      <div class="col-span-2">
        <img
          src="https://neilpubg.com/wp-content/uploads/2024/10/neilpubg.webp"
          alt="Logo"
          class="h-10 mb-3" />
        <p class="text-gray-600 play-regular text-base">
          <strong>TUNGMMO</strong> là một hệ thống mua bán tài khoản đáng
          tin cậy và uy tín, cung cấp các tài khoản phù hợp cho bạn ở nhiều
          nền tảng khác nhau. Nơi đây bạn có thể tìm kiếm và mua các tài
          khoản chất lượng từ những người bán đã được xác minh với cam kết
          đảm bảo tính bảo mật và an toàn cho giao dịch của bạn.
        </p>
      </div>

      <!-- Account Categories Section -->
      <div class="col-span-1">
        <h4 class="text-gray-600 play-regular text-lg font-bold mb-3">
          Danh mục tài khoản
        </h4>
        <ul class="text-gray-500 play-regular text-base space-y-2">
          <li>
            <a href="/tai-khoan-lien-quan" class="hover:underline">Mua tài khoản <strong>Liên Quân</strong></a>
          </li>
          <li>
            <a href="/tai-khoan-roblox" class="hover:underline">Mua tài khoản <strong>Roblox</strong></a>
          </li>
          <li>
            <a href="/tai-khoan-free-fire" class="hover:underline">Mua tài khoản <strong>Free Fire</strong></a>
          </li>
          <li>
            <a href="/tai-khoan-genshin-impact" class="hover:underline">Mua tài khoản <strong>Genshin Impact</strong></a>
          </li>
        </ul>
      </div>

      <!-- Links Section -->
      <div class="col-span-1">
        <h4 class="text-gray-600 play-regular text-lg font-bold mb-3">
          Liên kết
        </h4>
        <ul class="text-gray-500 play-regular text-base space-y-2">
          <li><a href="/blog" class="hover:underline">Bài viết</a></li>
          <li>
            <a
              href="/blog/huong-dan-mo-shop-ban-acc-mien-phi"
              class="hover:underline">Hướng dẫn mở Shop</a>
          </li>
          <li>
            <a
              href="//sieulike.me"
              target="_blank"
              rel="nofollow"
              class="hover:underline">Hệ thống dịch vụ mạng xã hội</a>
          </li>
        </ul>
      </div>

      <!-- Support Section -->
      <div class="col-span-1">
        <h4 class="text-gray-600 play-regular text-lg font-bold mb-3">
          Cộng đồng
        </h4>
        <ul class="text-gray-500 play-regular text-base space-y-2">
          <li>
            <a
              href="https://www.facebook.com/TUNGMMO"
              target="_blank"
              class="hover:underline">Nhóm Telegram</a>
          </li>
          <li>
            <a
              href="https://www.facebook.com/groups/TUNGMMO"
              target="_blank"
              class="hover:underline">Nhóm Zalo</a>
          </li>
          <li>
            <a
              href="https://m.me/TUNGMMO"
              target="_blank"
              class="hover:underline">Nhóm Messenger</a>
          </li>
        </ul>
      </div>
      <div class="col-span-1">
        <h4 class="text-gray-600 play-regular text-lg font-bold mb-3">
          Hỗ trợ
        </h4>
        <ul class="text-gray-500 play-regular text-base space-y-2">
          <li>
            <a
              href="https://www.facebook.com/TUNGMMO"
              target="_blank"
              class="hover:underline">Fanpage</a>
          </li>
          <li>
            <a
              href="https://www.facebook.com/groups/TUNGMMO"
              target="_blank"
              class="hover:underline">Zalo</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="bg-blue-500">
    <div
      class="container mx-auto play-regular py-2 text-center text-white text-base">
      <strong>TUNGMMO</strong> - All rights reserved.
    </div>
  </div>
</footer>