<?php
include_once __DIR__ . '/../layouts/head.phtml';
include_once __DIR__ . '/../layouts/navbar.phtml';
include_once __DIR__ . '/../layouts/sidebar.phtml';

?>
<!-- .app-main -->
<main class="app-main">
    <!-- .wrapper -->
    <div class="wrapper">
        <!-- .page -->
        <div class="page">
            <!-- .page-inner -->
            <div class="page-inner">
                <div class="page-section">
                    <div class="card card-fluid">
                        <h6 class="card-header">Sửa loại tài khoản</h6>
                        <!-- .card-body -->
                        <div class="card-body">
                            <form method="post" action="/api/admin/account/<?=$get->id;?>/edit" data-ajax="">
                                <div class="form-group mb-4">
                                    <div class="form-label-group">
                                        <input type="text" id="name" name="name" class="form-control placeholder-shown" value="<?=$get->name;?>" autocomplete="off" data-parsley-group="fieldset01" required="">
                                        <label for="name">Tên loại tài khoản</label>
                                    </div>
                                    <hr>
                                    <!-- .form-actions -->
                                    <div class="form-actions">
                                        <button type="submit" class="btn btn-primary ml-auto">
                                            Cập nhập
                                        </button>
                                    </div>
                                    <!-- /.form-actions -->
                            </form>
                            <!-- /form -->
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>

            </div><!-- /.page-inner -->
        </div><!-- /.page -->
    </div><!-- .app-footer -->

    <!-- /.wrapper -->
</main><!-- /.app-main -->

<?php
include_once __DIR__ . '/../layouts/footer.phtml';
include_once __DIR__ . '/../layouts/script.phtml';
include_once __DIR__ . '/../layouts/end.phtml';
?>